export default {

  CURRENT_USER_RECEIVED: 'CURRENT_USER_RECEIVED',
  PROFILE_CREATED: 'PROFILE_CREATED',

  CURRENT_HIKE_RECEIVED: 'CURRENT_HIKE_RECEIVED',
  HIKES_RECEIVED: 'HIKES_RECEIVED',
  HIKE_SELECTED: 'HIKE_SELECTED',
  LOCATION_ADDED: 'LOCATION_ADDED',

}
