export default {

  // General
  APPLICATION_STATE: 'APPLICATION_STATE',
  MESSAGE_RECEIVED: 'MESSAGE_RECEIVED',

  // Account
  CURRENT_USER_RECEIVED: 'CURRENT_USER_RECEIVED',
  PROFILE_CREATED: 'PROFILE_CREATED',

  // Hikes / Map
  CURRENT_HIKE_RECEIVED: 'CURRENT_HIKE_RECEIVED',
  HIKE_ADDED: 'HIKE_ADDED',
  HIKE_CREATED: 'HIKE_CREATED',
  HIKES_RECEIVED: 'HIKES_RECEIVED',
  USER_LOCATION_RECEIVED: 'USER_LOCATION_RECEIVED',

  // Profile
  PROFILE_RECEIVED: 'PROFILE_RECEIVED',

  // Reviews
  REVIEW_UPDATED: 'REVIEW_UPDATED',
  REVIEW_ADDED: 'REVIEW_ADDED',
  REVIEW_RECEIVED:'REVIEW_RECEIVED',
  REVIEWS_RECEIVED: 'REVIEWS_RECEIVED',


  HIKE_SELECTED: 'HIKE_SELECTED',
  LOCATION_ADDED: 'LOCATION_ADDED',


}
